// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8lmdWoJcovbJgKba0JNHEUSQ-0-hdkWc',
    appId: '1:597973554806:web:c0e59be055e1d77d7b7157',
    messagingSenderId: '597973554806',
    projectId: 'messageboardapp-ae38d',
    authDomain: 'messageboardapp-ae38d.firebaseapp.com',
    storageBucket: 'messageboardapp-ae38d.firebasestorage.app',
    measurementId: 'G-Y20T57FKK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLVllGk1VO_9JFIMXrn36VY4DTs3T_8nc',
    appId: '1:597973554806:android:61ad17affcfd2e047b7157',
    messagingSenderId: '597973554806',
    projectId: 'messageboardapp-ae38d',
    storageBucket: 'messageboardapp-ae38d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWaG9bKZVik9X9V1U9f7FL5-e9tdsCD6M',
    appId: '1:597973554806:ios:f6b796edcfe5f6a17b7157',
    messagingSenderId: '597973554806',
    projectId: 'messageboardapp-ae38d',
    storageBucket: 'messageboardapp-ae38d.firebasestorage.app',
    iosClientId: '597973554806-e2r0mj1t8qk2nnb7qner63sdlsqnpoc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWaG9bKZVik9X9V1U9f7FL5-e9tdsCD6M',
    appId: '1:597973554806:ios:f6b796edcfe5f6a17b7157',
    messagingSenderId: '597973554806',
    projectId: 'messageboardapp-ae38d',
    storageBucket: 'messageboardapp-ae38d.firebasestorage.app',
    iosClientId: '597973554806-e2r0mj1t8qk2nnb7qner63sdlsqnpoc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8lmdWoJcovbJgKba0JNHEUSQ-0-hdkWc',
    appId: '1:597973554806:web:3583b7bd76a2ef1b7b7157',
    messagingSenderId: '597973554806',
    projectId: 'messageboardapp-ae38d',
    authDomain: 'messageboardapp-ae38d.firebaseapp.com',
    storageBucket: 'messageboardapp-ae38d.firebasestorage.app',
    measurementId: 'G-RYSE6SKP3E',
  );

}